### PR TITLE
Changes to provinces of Ireland and added county output in API

### PR DESCRIPTION
**Pull request by Kattixie**
Hello!

I noticed during a recent project that I was getting US states back for IE/Ireland users. I went ahead and replaced the states with provinces of Ireland, but I get the impression the provinces are more historical and cultural than administrative.

Until recently, I believe it was more common for counties to be used for addresses ([source](http://www.columbia.edu/~fdc/postal/#ireland)), so I added this property to the API in the event that a county list exists. I can see an argument to use counties as "states," too, in the case of Ireland. It definitely gets tricky! Let me know if you'd like to take a different route here.

ALSO I couldn't figure out how to load the .nextRelease files (instead of 1.0) so check that carefully! THANK YOU for all of your efforts!

### CODE REVIEW

**Comment by keitharm** [comment]
Hi @Kattixie,

I think that in the case of Ireland, counties should be used in place of provinces for the states property. Also, even though it'd be more appropriate for counties to have their own counties property, a goal of all the nationalities is to have consistent property names. With that in mind, I think that the data in the counties list should be moved to the states list, the closest match for a county.

In regards to .nextRelease, you can make your changes in the 1.0 directory. I am planning on removing .nextRelease since it is a little confusing what goes where and also version changes will be for API changing updates, not data updates.

Thanks!

**Comment by Kattixie** [comment]
This sounds good! I reverted my changes, copied the contents of counties.txt to states.txt in the IE folder, and deleted counties.txt (since it's not getting used for now). I attempted a rebase here and hopefully I did it right... :)

**Comment by keitharm** [comment]
Looks good, thanks for the fix! :)

**Comment by Kattixie** [comment]
Thank you! :D Keep up the great work.

**Pull request merged**
